{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5ad7830b",
   "metadata": {},
   "outputs": [],
   "source": [
    "while True:\n",
    "    user_input = input(\">  \")\n",
    "    try:\n",
    "        exec(user_input)\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "360b3bb6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 14, in execute_code\n",
      "    exec(user_code)  # Execute the user's code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 19, in execute_code\n",
      "    output_text.insert(\"insert\", f\"Error: {str(e)}\\n\")\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 14, in execute_code\n",
      "    exec(user_code)  # Execute the user's code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 19, in execute_code\n",
      "    output_text.insert(\"insert\", f\"Error: {str(e)}\\n\")\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 14, in execute_code\n",
      "    exec(user_code)  # Execute the user's code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 19, in execute_code\n",
      "    output_text.insert(\"insert\", f\"Error: {str(e)}\\n\")\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"<string>\", line 14, in execute_code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<string>\", line 19, in execute_code\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 14, in execute_code\n",
      "    exec(user_code)  # Execute the user's code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 19, in execute_code\n",
      "    output_text.insert(\"insert\", f\"Error: {str(e)}\\n\")\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"<string>\", line 14, in execute_code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<string>\", line 19, in execute_code\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 14, in execute_code\n",
      "    exec(user_code)  # Execute the user's code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 19, in execute_code\n",
      "    output_text.insert(\"insert\", f\"Error: {str(e)}\\n\")\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"<string>\", line 14, in execute_code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<string>\", line 19, in execute_code\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 14, in execute_code\n",
      "    exec(user_code)  # Execute the user's code\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 27, in write\n",
      "    self.text_widget.insert(\"end\", text)\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/tmp/ipykernel_470/3794276674.py\", line 19, in execute_code\n",
      "    output_text.insert(\"insert\", f\"Error: {str(e)}\\n\")\n",
      "  File \"/usr/lib/python3.10/tkinter/__init__.py\", line 3782, in insert\n",
      "    self.tk.call((self._w, 'insert', index, chars) + args)\n",
      "_tkinter.TclError: invalid command name \".!text2\"\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "\n",
    "# Your own code goes here\n",
    "\n",
    "\n",
    "def execute_code():\n",
    "    user_code = code_text.get(\"1.0\", \"end-1c\")  # Get code from the text area\n",
    "    try:\n",
    "        # Redirect the standard output to our Text widget\n",
    "        import sys\n",
    "        original_stdout = sys.stdout\n",
    "        sys.stdout = TextRedirector(output_text)\n",
    "\n",
    "        exec(user_code)  # Execute the user's code\n",
    "\n",
    "        # Restore the standard output\n",
    "        sys.stdout = original_stdout\n",
    "    except Exception as e:\n",
    "        output_text.insert(\"insert\", f\"Error: {str(e)}\\n\")\n",
    "\n",
    "# Create a custom text widget to redirect stdout\n",
    "class TextRedirector:\n",
    "    def __init__(self, text_widget):\n",
    "        self.text_widget = text_widget\n",
    "\n",
    "    def write(self, text):\n",
    "        self.text_widget.insert(\"end\", text)\n",
    "        self.text_widget.see(\"end\")\n",
    "\n",
    "# Create the main window\n",
    "root = tk.Tk()\n",
    "root.title(\"Neptune Notebook\")\n",
    "\n",
    "# Create a text area for code input\n",
    "code_text = tk.Text(root, width=80, height=20)\n",
    "code_text.pack()\n",
    "\n",
    "# Create a button to execute the code\n",
    "execute_button = tk.Button(root, text=\"Run Code\", command=execute_code)\n",
    "execute_button.pack()\n",
    "\n",
    "# Create an output console\n",
    "output_text = tk.Text(root, width=80, height=10)\n",
    "output_text.pack()\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e5a7fbe",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9acb9341",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
